import {
  Add01Icon,
  AlertCircleIcon,
  ArrowRight01Icon,
  Cancel01Icon,
  Chart01Icon,
  CheckmarkCircle02Icon,
  CpuIcon,
  Database01Icon,
  Delete02Icon,
  DocumentCodeIcon,
  FlowIcon,
  InboxIcon,
  Layers01Icon,
  Loading03Icon,
  MoreHorizontalIcon,
  Package01Icon,
  PencilEdit01Icon,
  PlayIcon,
  Robot01Icon,
  SparklesIcon,
  Tag01Icon,
  Upload01Icon,
} from "@hugeicons/core-free-icons";

import { makeIcon } from "./icon";

export const icons = {
  dataset: makeIcon(Database01Icon),
  item: makeIcon(InboxIcon),
  scheme: makeIcon(Tag01Icon),
  annotate: makeIcon(PencilEdit01Icon),
  pipeline: makeIcon(FlowIcon),
  block: makeIcon(Layers01Icon),
  run: makeIcon(PlayIcon),
  metrics: makeIcon(Chart01Icon),
  model: makeIcon(CpuIcon),
  artifact: makeIcon(Package01Icon),
  llm: makeIcon(Robot01Icon),
  sparkles: makeIcon(SparklesIcon),
  add: makeIcon(Add01Icon),
  remove: makeIcon(Delete02Icon),
  close: makeIcon(Cancel01Icon),
  next: makeIcon(ArrowRight01Icon),
  done: makeIcon(CheckmarkCircle02Icon),
  spinner: makeIcon(Loading03Icon),
  upload: makeIcon(Upload01Icon),
  config: makeIcon(DocumentCodeIcon),
  more: makeIcon(MoreHorizontalIcon),
  error: makeIcon(AlertCircleIcon),
} as const;
