services:
  es:
    container_name: olim_es
    image: docker.elastic.co/elasticsearch/elasticsearch:8.7.0
    volumes:
      - data:/usr/share/elasticsearch/data
    environment:
      - node.name=olim_es
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - xpack.security.enabled=false
      - xpack.security.enrollment.enabled=false
    mem_limit: 4G
    restart: unless-stopped
    networks:
      - olim-es

  olim:
    image: olim
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 42000:42000
    environment:
      - ES_SERVER=http://olim_es:9200
      - DEBUG=true
      - LEARNER_URL=http://olim-learner:42010
      # Run `docker compose exec olim-learner poetry run flask --app api app-keys new data/sample_data.csv text_id text`
      # on the learner directory to upload data to it and get the key
      - LEARNER_KEY=
      - LABELS=LABELS_TYPES.YES_NO
    restart: unless-stopped
    networks:
      - olim-es
      # Uncoment this network if you are running the learner on the same machine on Docker
      # - olim-learner_main

volumes:
  data:
    driver: local

networks:
  olim-es:
    driver: bridge
  # Uncoment this network if you are running the learner on the same machine on Docker
  # olim-learner_main:
  #   external: true
