# Docker Compose override for debugging
# Usage: docker compose -f docker-compose.yml -f docker-compose.debug.yml up
services:
  olim:
    volumes:
      - .:/app

  db:
    ports:
      - '${POSTGRES_PORT:-5432}:5432'

  es:
    ports:
      - '9200:9200'
      - '9300:9300'
