"""create sessions table

Revision ID: 036595491aee
Revises: 24287f3ca93e
Create Date: 2025-05-15 22:02:43.056257

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '036595491aee'
down_revision = '24287f3ca93e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(length=255), nullable=True),
    sa.Column('data', sa.LargeBinary(), nullable=True),
    sa.Column('expiry', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id')
    )
    with op.batch_alter_table('entries', schema=None) as batch_op:
        batch_op.drop_constraint('entries_entry_id_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('entries', schema=None) as batch_op:
        batch_op.create_unique_constraint('entries_entry_id_key', ['entry_id'])

    op.drop_table('sessions')
    # ### end Alembic commands ###
