"""Fixed relations, added user session

Revision ID: 24287f3ca93e
Revises: 0c02d3746739
Create Date: 2025-05-14 16:13:58.828088

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "24287f3ca93e"
down_revision = "0c02d3746739"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("labels", schema=None) as batch_op:
        batch_op.add_column(sa.Column("project_id", sa.Integer(), nullable=False))
        batch_op.create_foreign_key(
            "fk_project_id", "projects", ["project_id"], ["id"]
        )

    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.add_column(sa.Column("session_data", sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_column("session_data")

    with op.batch_alter_table("labels", schema=None) as batch_op:
        batch_op.drop_constraint("fk_project_id", type_="foreignkey")
        batch_op.drop_column("project_id")

    # ### end Alembic commands ###
