"""Add label_type and label_settings to labels

Revision ID: 69207104f4a6
Revises: cd97c2bcac12
Create Date: 2025-09-24 15:09:59.353293

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69207104f4a6'
down_revision = 'cd97c2bcac12'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('labels', schema=None) as batch_op:
        batch_op.add_column(sa.Column('label_type', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('label_settings', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('labels', schema=None) as batch_op:
        batch_op.drop_column('label_settings')
        batch_op.drop_column('label_type')

    # ### end Alembic commands ###
