"""Added language and active learning columns

Revision ID: 714e414e5b06
Revises: 
Create Date: 2023-11-09 19:37:07.082954

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '714e414e5b06'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('labels', schema=None) as batch_op:
        batch_op.add_column(sa.Column('al_key', sa.String(), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('language', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('language')

    with op.batch_alter_table('labels', schema=None) as batch_op:
        batch_op.drop_column('al_key')

    # ### end Alembic commands ###
