"""Add learning_tasks table

Revision ID: a82bba690b03
Revises: d2e8740f1dbf
Create Date: 2026-02-03 20:55:28.957816

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a82bba690b03'
down_revision = 'd2e8740f1dbf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('learning_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('state', sa.String(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False, server_default='0'),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('initial_setup', sa.JSON(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name='fk_created_by'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name='fk_learning_task_project'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('learning_tasks')
    # ### end Alembic commands ###
