"""Add priority column to labels table

Revision ID: b607167a4dcb
Revises: 714e414e5b06
Create Date: 2025-03-24 20:45:32.058246

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b607167a4dcb'
down_revision = '714e414e5b06'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('labels', schema=None) as batch_op:
        batch_op.add_column(sa.Column('priority', sa.Float(), nullable=False, server_default='1.0'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('labels', schema=None) as batch_op:
        batch_op.drop_column('priority')

    # ### end Alembic commands ###
