"""create ml models management tables

Revision ID: bfb791bf358b
Revises: d2e8740f1dbf
Create Date: 2026-02-17 14:41:35.836787

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'bfb791bf358b'
down_revision = 'd2e8740f1dbf'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ml_models',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('label_id', sa.Integer(), nullable=True),
    sa.Column('model_type', sa.String(), nullable=False),
    sa.Column('algorithm', sa.String(), nullable=False),
    sa.Column('model_config', sa.JSON(), nullable=False),
    sa.Column('training_config', sa.JSON(), nullable=False),
    sa.Column('policy_type', sa.String(), nullable=True),
    sa.Column('subsample_config', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name='fk_created_by'),
    sa.ForeignKeyConstraint(['label_id'], ['labels.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ml_models', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ml_models_label_id'), ['label_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ml_models_slug'), ['slug'], unique=True)
        batch_op.create_index(batch_op.f('ix_ml_models_status'), ['status'], unique=False)

    op.create_table('ml_model_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model_id', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('artifact_path', sa.String(), nullable=False),
    sa.Column('trained_at', sa.DateTime(), nullable=False),
    sa.Column('training_duration', sa.Float(), nullable=True),
    sa.Column('n_train_samples', sa.Integer(), nullable=False),
    sa.Column('n_val_samples', sa.Integer(), nullable=False),
    sa.Column('class_distribution', sa.JSON(), nullable=True),
    sa.Column('metrics', sa.JSON(), nullable=False),
    sa.Column('conformal_threshold', sa.Float(), nullable=True),
    sa.Column('cache_entries', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name='fk_created_by'),
    sa.ForeignKeyConstraint(['model_id'], ['ml_models.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('model_id', 'version', name='uq_model_version')
    )
    with op.batch_alter_table('ml_model_versions', schema=None) as batch_op:
        batch_op.create_index(
            'ix_ml_model_versions_active', ['model_id', 'is_active'], unique=False
        )
        batch_op.create_index('ix_ml_model_versions_trained', ['trained_at'], unique=False)

    op.create_table('ml_training_jobs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('model_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('version_id', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('config_snapshot', sa.JSON(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name='fk_created_by'),
    sa.ForeignKeyConstraint(['model_id'], ['ml_models.id'], ),
    sa.ForeignKeyConstraint(['version_id'], ['ml_model_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ml_training_jobs', schema=None) as batch_op:
        batch_op.create_index('ix_ml_training_jobs_model', ['model_id'], unique=False)
        batch_op.create_index('ix_ml_training_jobs_status', ['status'], unique=False)

    op.create_table('ml_model_predictions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model_id', sa.Integer(), nullable=False),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.Column('input_text', sa.Text(), nullable=False),
    sa.Column('predicted_class', sa.String(), nullable=True),
    sa.Column('prediction_set', sa.JSON(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('class_probabilities', sa.JSON(), nullable=True),
    sa.Column('predicted_at', sa.DateTime(), nullable=False),
    sa.Column('external_request_id', sa.String(), nullable=True),
    sa.Column('entry_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['entry_id'], ['entries.id'], ),
    sa.ForeignKeyConstraint(['model_id'], ['ml_models.id'], ),
    sa.ForeignKeyConstraint(['version_id'], ['ml_model_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ml_model_predictions', schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f('ix_ml_model_predictions_external_request_id'),
            ['external_request_id'],
            unique=False,
        )
        batch_op.create_index('ix_ml_predictions_entry', ['entry_id'], unique=False)
        batch_op.create_index(
            'ix_ml_predictions_model_version', ['model_id', 'version_id'], unique=False
        )
        batch_op.create_index('ix_ml_predictions_predicted_at', ['predicted_at'], unique=False)

    with op.batch_alter_table('labels', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ml_model_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_labels_ml_model_id'), ['ml_model_id'], unique=False)
        batch_op.create_foreign_key(None, 'ml_models', ['ml_model_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('labels', schema=None) as batch_op:
        batch_op.drop_constraint('labels_ml_model_id_fkey', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_labels_ml_model_id'))
        batch_op.drop_column('ml_model_id')

    with op.batch_alter_table('ml_model_predictions', schema=None) as batch_op:
        batch_op.drop_index('ix_ml_predictions_predicted_at')
        batch_op.drop_index('ix_ml_predictions_model_version')
        batch_op.drop_index('ix_ml_predictions_entry')
        batch_op.drop_index(batch_op.f('ix_ml_model_predictions_external_request_id'))

    op.drop_table('ml_model_predictions')
    with op.batch_alter_table('ml_training_jobs', schema=None) as batch_op:
        batch_op.drop_index('ix_ml_training_jobs_status')
        batch_op.drop_index('ix_ml_training_jobs_model')

    op.drop_table('ml_training_jobs')
    with op.batch_alter_table('ml_model_versions', schema=None) as batch_op:
        batch_op.drop_index('ix_ml_model_versions_trained')
        batch_op.drop_index('ix_ml_model_versions_active')

    op.drop_table('ml_model_versions')
    with op.batch_alter_table('ml_models', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ml_models_status'))
        batch_op.drop_index(batch_op.f('ix_ml_models_slug'))
        batch_op.drop_index(batch_op.f('ix_ml_models_label_id'))

    op.drop_table('ml_models')
    # ### end Alembic commands ###
