"""Added label training data columns

Revision ID: c1d7d0b1a729
Revises: 036595491aee
Create Date: 2025-05-28 14:01:01.558389

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c1d7d0b1a729'
down_revision = '036595491aee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('labels', schema=None) as batch_op:
        batch_op.add_column(sa.Column('metrics', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('cache', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('training_counter', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('labels', schema=None) as batch_op:
        batch_op.drop_column('training_counter')
        batch_op.drop_column('cache')
        batch_op.drop_column('metrics')

    # ### end Alembic commands ###
