"""Add auto_labels column to Label model

Revision ID: cd97c2bcac12
Revises: d81ac9c15a59
Create Date: 2025-07-11 13:54:17.448910

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd97c2bcac12'
down_revision = 'd81ac9c15a59'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('labels', schema=None) as batch_op:
        batch_op.add_column(sa.Column('auto_labels', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('labels', schema=None) as batch_op:
        batch_op.drop_column('auto_labels')

    # ### end Alembic commands ###
