"""Add learner_parameters JSON column to labels

Revision ID: d81ac9c15a59
Revises: ddc5988f684a
Create Date: 2025-07-11 12:31:12.959433

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd81ac9c15a59'
down_revision = 'ddc5988f684a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('labels', schema=None) as batch_op:
        batch_op.add_column(sa.Column('learner_parameters', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('labels', schema=None) as batch_op:
        batch_op.drop_column('learner_parameters')

    # ### end Alembic commands ###
