"""Added task description.

Revision ID: ddc5988f684a
Revises: c1d7d0b1a729
Create Date: 2025-05-31 14:07:32.286134

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ddc5988f684a'
down_revision = 'c1d7d0b1a729'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('celery_tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(length=128), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('celery_tasks', schema=None) as batch_op:
        batch_op.drop_column('description')

    # ### end Alembic commands ###
