"""Added user.language and labels.al_key columns

Revision ID: e8eca55db06c
Revises: 7217cc881dbb
Create Date: 2025-03-27 19:40:20.808608

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e8eca55db06c'
down_revision = '7217cc881dbb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('labels', schema=None) as batch_op:
        batch_op.add_column(sa.Column('al_key', sa.String(), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('language', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('language')

    with op.batch_alter_table('labels', schema=None) as batch_op:
        batch_op.drop_column('al_key')

    # ### end Alembic commands ###
