"""Added labels.priority column

Revision ID: f2a646872d44
Revises: e8eca55db06c
Create Date: 2025-03-27 19:41:28.214426

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f2a646872d44'
down_revision = 'e8eca55db06c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('labels', schema=None) as batch_op:
        batch_op.add_column(sa.Column('priority', sa.Float(), nullable=False, server_default='1.0'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('labels', schema=None) as batch_op:
        batch_op.drop_column('priority')

    # ### end Alembic commands ###
