name: Code Quality

on:
  push:
    branches: [main]
  pull_request:
    branches: [main, dev]

jobs:
  prek-action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7.0.0
      - uses: j178/prek-action@v2.0.4
